export const userInfo = [
    {
        id: 1,
        name: "현실은백만년솔로",
        time: "3시간 19분",
        levelicon: "/image/common/userInfo/level_01.png",
        level: 31,
        userProfile: "/image/common/userInfo/userProfile_01.png",
    },
    {
        id: 2,
        name: "게임왕",
        time: "1시간 20분",
        levelicon: "/image/common/userInfo/level_02.png",
        level: 51,
        userProfile: "/image/common/userInfo/userProfile_02.png",
    },
    {
        id: 3,
        name: "즐겜러",
        time: "5시간 45분",
        levelicon: "/image/common/userInfo/level_03.png",
        level: 101,
        userProfile: "/image/common/userInfo/userProfile_03.png",
    },
    {
        id: 4,
        name: "코딩노예",
        time: "2시간 10분",
        levelicon: "/image/common/userInfo/level_04.png",
        level: 151,
        userProfile: "/image/common/userInfo/userProfile_04.png",
    },
    {
        id: 5,
        name: "배고파요",
        time: "4시간 00분",
        levelicon: "/image/common/userInfo/level_05.png",
        level: 201,
        userProfile: "/image/common/userInfo/userProfile_05.png",
    },
    {
        id: 6,
        name: "요로로로마이밥",
        time: "48시간 19분",
        levelicon: "/image/common/userInfo/level_01.png",
        level: 31,
        // Assuming typical mapping, adjusting as needed implies using available images
        userProfile: "/image/common/userInfo/userProfile_06.png",
    },
    {
        id: 7,
        name: "파란불빛",
        time: "35시간 46분",
        levelicon: "/image/common/userInfo/level_02.png",
        level: 27,
        userProfile: "/image/common/userInfo/userProfile_07.png",
    },
    {
        id: 8,
        name: "크런치맛있다",
        time: "150시간 33분",
        levelicon: "/image/common/userInfo/level_03.png",
        level: 121,
        userProfile: "/image/common/userInfo/userProfile_08.png",
    },
    {
        id: 9,
        name: "끄아아아아아",
        time: "253시간 28분",
        levelicon: "/image/common/userInfo/level_04.png",
        level: 203,
        userProfile: "/image/common/userInfo/userProfile_09.png",
    }
];
